language: node_js
node_js:
  - 14

install:
  - make install

script:
  - make test
  - make build

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  verbose: true
  fqdn: statium.app
  on:
    repo: statium-app/statium-webapp
    branch: master

cache:
  yarn: true
